### ISSUE TITLE
All the methods return strings

### ISSUE THREAD

**Issue by fstanis** [jamesnetherton/homehub-client#8]
I wanted to use this library for a small project, but I find it a bit strange all the methods actually return `string` instead of something more structured. It would be far more useful if e.g. `ConnectedDevices` returned a slice of structs that I could enumerate in order to get information about a particular device.

**Comment by jamesnetherton** [comment]
Yes, I've been thinking the same thing. Should probably also modify the return types for functions that return numeric types etc.

I'll look into it.

**Comment by fstanis** [comment]
Thank you. I think a simple solution would be to just make the structs in `request.go` public and expose them directly from the public methods (or alternatively making copies of them with less fields).

**Comment by jamesnetherton** [comment]
I pushed up some first steps towards improving this. All Hub functions should now return types that are appropriate for their associated Hub method invocation.

Quick summary of changes:

* `ConnectedDevices` returns an Array of [`DeviceDetail`](https://github.com/jamesnetherton/homehub-client/blob/master/request.go#L64-L93) objects
* `DeviceInfo` returns an [ `DeviceDetail`](https://github.com/jamesnetherton/homehub-client/blob/master/request.go#L64-L93) object
* `EventLog` returns an [`EventLog`](https://github.com/jamesnetherton/homehub-client/blob/master/event_log.go#L9-L11) object which contains an array of type [`EventLogEntry`](https://github.com/jamesnetherton/homehub-client/blob/master/event_log.go#L14-L19)
* Other methods return either `string`, `int`, `int64` or `bool`

Need to tidy a few things up before I cut a tag for this, but the basics are there.

**Comment by jamesnetherton** [comment]
I just cut a `v0.3.0` tag for these changes. 

Tested in my [homehub-cli](https://github.com/jamesnetherton/homehub-cli) project and it all seems to work fine.
